name: recipes
description: A new Flutter project.

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  image_picker: ^0.6.5+2
  cloud_firestore: ^0.13.5
  font_awesome_flutter: ^8.8.1
  firebase_auth: ^0.16.0
  firebase_storage: ^3.1.5
  date_format: ^1.0.8
  intl: ^0.16.1
  modal_progress_hud: ^0.1.3
  intro_slider: ^2.2.9
  path_provider: ^1.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
       - assets/images/